name: translate

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - beta

jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      - uses: jeedomThirdPartyDevs/plugins-translations@v0.11
        with:
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
