name: translate

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - beta

jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      - uses: jeedomThirdPartyDevs/plugins-translations@v0.10
        with:
          token: ${{ secrets.TRANSLATION_TOKEN }}
